version: '3.8'

networks:
  auth-events:
    name: auth-events

services:
  auth-events.microservice:
    build:
      context: ./
      dockerfile: src/AuthEvents/Dockerfile
    restart: unless-stopped
    depends_on: 
      - "auth-events.postgres"
    ports:
      - "${API_HOST:-127.0.0.1}:${API_PORT}:80"
    networks:
      - auth-events
    env_file:
      - .env

  auth-events.postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${PG_DB:-events_db}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASS}"
      PGDATA: "/var/lib/pgsql/data"
    volumes:
      - ${PG_DATA:-/opt/auth-events/pgsql/data}:/var/lib/pgsql/data
    ports:
      - "${POSTGRES_HOST:-127.0.0.1}:${POSTGRES_PORT}:5432"
    networks:
      - auth-events
    env_file:
      - .env
